development:
  clients:
    default:
      database: admin
      hosts:
        - 127.0.0.1:27017
      options:
  options:

production:
  clients:
    default:
      database: admin
      hosts:
        - 127.0.0.1:27017
      options:
  options:

test:
  clients:
    default:
      database: ramirez
      hosts:
        - 127.0.0.1:27017
      options:
  options:
