# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "127.0.0.1:27017"
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Give Permissions
        run: |
          chmod u+x bin/rails
          chmod u+x bin/bundle
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:seed
      # Add or replace test runners here
      - name: Run tests
        run: bin/bundle exec rspec -f progress

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Give Permissions
        run: |
          chmod u+x bin/rails
          chmod u+x bin/bundle
      - name: Lint Ruby files
        run: bin/bundle exec rubocop --parallel --autocorrect

  doc:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Install Ruby and gems
       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
       with:
          ruby-version: '3.2'
          bundler-cache: true
     - name: Give Permissions
       run: |
          chmod u+x bin/rails
          chmod u+x bin/bundle
     - name: Generate Documentation
       run: bin/bundle exec yardoc -o docs
